# Generated by Django 4.1.2 on 2022-11-11 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('created_on', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_status', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Message_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_status', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Message_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_description', models.TextField()),
                ('recommended_test', models.TextField()),
                ('created_on', models.DateTimeField(verbose_name='date created')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customermanagement.customer_product')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_telephone', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('customer_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customermanagement.customer_status')),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customermanagement.customer_type')),
            ],
        ),
        migrations.AddField(
            model_name='customer_product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customermanagement.product_type'),
        ),
        migrations.CreateModel(
            name='Customer_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_token', models.CharField(max_length=200)),
                ('message_subject', models.CharField(max_length=200)),
                ('message_body', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=200)),
                ('date_sent', models.DateTimeField(verbose_name='date sent')),
                ('date_received', models.DateTimeField(verbose_name='date received')),
                ('message_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customermanagement.message_status')),
                ('recepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
