# Generated by Django 4.1.3 on 2022-12-17 12:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Person_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 718286), verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 728285), verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_status', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 714284), verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 712286), verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Message_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_status', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 723284), verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Message_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 722285), verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 727284), verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_description', models.TextField()),
                ('recommended_test', models.TextField(null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 730286), verbose_name='date created')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_requirements', to='customermanagement.customer_product')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_telephone', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('registration_number', models.CharField(max_length=200, null=True)),
                ('postal_code', models.CharField(max_length=200, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 716269), verbose_name='date created')),
                ('customer_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customermanagement.customer_status')),
                ('customer_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customermanagement.customer_type')),
            ],
        ),
        migrations.AddField(
            model_name='customer_product',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_products', to='customermanagement.customer_profile'),
        ),
        migrations.AddField(
            model_name='customer_product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customermanagement.product_type'),
        ),
        migrations.CreateModel(
            name='Customer_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_subject', models.CharField(max_length=200)),
                ('message_body', models.CharField(max_length=200)),
                ('date_sent', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 724284), verbose_name='date sent')),
                ('date_received', models.DateTimeField(null=True, verbose_name='date received')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_messages', to='customermanagement.customer_profile')),
                ('message_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customermanagement.message_status')),
                ('recepient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200, null=True)),
                ('registration_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 720285), verbose_name='registration date')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contact_persons', to='customermanagement.customer_profile')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customermanagement.contact_person_status')),
            ],
        ),
    ]
