# Generated by Django 4.1.2 on 2022-12-11 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_message',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='customer_message',
            name='message_token',
        ),
        migrations.AddField(
            model_name='customer_message',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customermanagement.customer_profile'),
        ),
        migrations.AddField(
            model_name='customer_product',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customermanagement.customer_profile'),
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 16, 22, 4, 706889), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='customer_message',
            name='date_received',
            field=models.DateTimeField(null=True, verbose_name='date received'),
        ),
        migrations.AlterField(
            model_name='customer_message',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 16, 22, 4, 712913), verbose_name='date sent'),
        ),
        migrations.AlterField(
            model_name='customer_message',
            name='message_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customermanagement.message_status'),
        ),
        migrations.AlterField(
            model_name='customer_product',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 16, 22, 4, 716913), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='customer_product',
            name='product_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer_product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customermanagement.product_type'),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='customer_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='customer_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customermanagement.customer_status'),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='customer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customermanagement.customer_type'),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='postal_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='registration_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 16, 22, 4, 703890), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='customer_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 16, 22, 4, 702888), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='message_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 16, 22, 4, 711895), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='message_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 16, 22, 4, 708898), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='product_requirements',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 16, 22, 4, 718909), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='product_requirements',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customermanagement.customer_product'),
        ),
        migrations.AlterField(
            model_name='product_requirements',
            name='recommended_test',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 16, 22, 4, 714911), verbose_name='date created'),
        ),
    ]
