# Generated by Django 4.1.3 on 2022-12-14 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customermanagement', '0002_remove_customer_message_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_message',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 720949), verbose_name='date sent'),
        ),
        migrations.AlterField(
            model_name='customer_product',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 724947), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 714930), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='customer_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 712931), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='customer_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 710874), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='message_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 718930), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='message_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 717929), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='product_requirements',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 726945), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 722946), verbose_name='date created'),
        ),
    ]
