# Generated by Django 4.1.3 on 2022-12-18 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customermanagement', '0002_rename_url_customer_profile_customer_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_person',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 533632), verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='contact_person_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 531630), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='customer_message',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 538629), verbose_name='date sent'),
        ),
        migrations.AlterField(
            model_name='customer_product',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 542631), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 529633), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='customer_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 527631), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='customer_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 525636), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='message_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 536629), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='message_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 535629), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='product_requirements',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 544630), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 540630), verbose_name='date created'),
        ),
    ]
