# Generated by Django 4.1.3 on 2022-12-14 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customermanagement', '0003_alter_customer_message_date_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_message',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 18, 432658), verbose_name='date sent'),
        ),
        migrations.AlterField(
            model_name='customer_product',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 18, 437635), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 18, 427657), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='customer_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 18, 425659), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='customer_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 18, 423656), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='message_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 18, 430657), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='message_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 18, 429658), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='product_requirements',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 18, 441655), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 18, 435648), verbose_name='date created'),
        ),
    ]
