# Generated by Django 4.1.3 on 2022-12-17 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Development_Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=200)),
                ('justification', models.TextField(null=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 789217), verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Development_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Development_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 784215), verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Development_Team_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_definition', models.TextField()),
                ('release_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 795215), verbose_name='release date')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_product_releases', to='developer.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 767214), verbose_name='creation date')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_managers', to='developer.project')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.TextField()),
                ('deliverable', models.TextField(null=True)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 772215), verbose_name='deadline')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 772215), verbose_name='creation date')),
                ('plan_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_project_plans', to='scrummaster.project_manager')),
                ('plan_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority_project_plans', to='scrummaster.priority')),
                ('plan_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.plan_status')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_plans', to='developer.project')),
            ],
        ),
        migrations.CreateModel(
            name='Release_Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField()),
                ('release_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 797215), verbose_name='feature release date')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority_release_features', to='scrummaster.priority')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='release_features', to='scrummaster.product_release')),
            ],
        ),
        migrations.CreateModel(
            name='Release_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Risk_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Member_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Member_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 787213), verbose_name='creation date')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 787213), verbose_name='start date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 787213), verbose_name='end date')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_team_memberships', to='developer.developer')),
                ('member_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_team_members', to='scrummaster.team_member_role')),
                ('member_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.team_member_status')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='scrummaster.development_team')),
            ],
        ),
        migrations.CreateModel(
            name='Release_Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.TextField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 799214), verbose_name='creation date')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_release_strategies', to='scrummaster.release_feature')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_release_strategies', to='scrummaster.project_manager')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='release_strategies', to='scrummaster.product_release')),
            ],
        ),
        migrations.CreateModel(
            name='Release_Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlog', models.TextField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 801212), verbose_name='creation date')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_release_backlogs', to='scrummaster.project_manager')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_release_backlogs', to='scrummaster.release_strategy')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Plan_Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.TextField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 775215), verbose_name='creation date')),
                ('project_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_plan_risks', to='scrummaster.project_plan')),
                ('risk_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_project_plan_risks', to='scrummaster.project_manager')),
                ('risk_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority_project_plan_risks', to='scrummaster.priority')),
                ('risk_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.risk_status')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_skills', models.TextField(null=True)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 779213), verbose_name='deadline')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 779213), verbose_name='creation date')),
                ('development_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dev_plan_implementations', to='scrummaster.project_plan')),
                ('development_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.development_status')),
                ('scrum_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrummaster_project_developments', to='scrummaster.project_manager')),
            ],
        ),
        migrations.AddField(
            model_name='product_release',
            name='release_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.release_status'),
        ),
        migrations.AddField(
            model_name='development_team',
            name='project_development',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dev_teams', to='scrummaster.project_development'),
        ),
        migrations.AddField(
            model_name='development_team',
            name='team_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.development_team_status'),
        ),
        migrations.CreateModel(
            name='Development_Rule_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 15, 3, 13, 792214), verbose_name='creation date')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_dev_rule_feedbacks', to='developer.developer')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dev_rule_feedbacks', to='scrummaster.development_rule')),
            ],
        ),
        migrations.AddField(
            model_name='development_rule',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_dev_rules', to='scrummaster.project_manager'),
        ),
        migrations.AddField(
            model_name='development_rule',
            name='project_development',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_dev_rules', to='scrummaster.project_development'),
        ),
    ]
