# Generated by Django 4.1.3 on 2022-12-18 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrummaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development_rule',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 605629), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='development_rule_feedback',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 608631), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='development_team',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 599631), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='product_release',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 611630), verbose_name='release date'),
        ),
        migrations.AlterField(
            model_name='project_development',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 594629), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project_development',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 594629), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='project_manager',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 581634), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project_plan',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 586631), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project_plan',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 586631), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='project_plan_risk',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 591630), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='release_backlog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 617629), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='release_feature',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 613630), verbose_name='feature release date'),
        ),
        migrations.AlterField(
            model_name='release_strategy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 615631), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 603631), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 603631), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 603631), verbose_name='start date'),
        ),
    ]
