# Generated by Django 4.1.3 on 2022-12-14 19:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customermanagement', '0003_alter_customer_message_date_sent_and_more'),
        ('scrummaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_recepient',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedback_recepient',
            name='recepient',
        ),
        migrations.RemoveField(
            model_name='feedback_recepient',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product_release',
            name='release_backlog',
        ),
        migrations.RemoveField(
            model_name='product_release',
            name='release_strategy',
        ),
        migrations.AddField(
            model_name='contact_person',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customermanagement.customer_profile'),
        ),
        migrations.AddField(
            model_name='release_backlog',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.release_strategy'),
        ),
        migrations.AddField(
            model_name='release_strategy',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.release_feature'),
        ),
        migrations.AddField(
            model_name='release_strategy',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.product_release'),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 803956), verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.contact_person_status'),
        ),
        migrations.AlterField(
            model_name='contact_person_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 800931), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='development_rule',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 836954), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='development_rule',
            name='justification',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='development_rule',
            name='made_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.project_manager'),
        ),
        migrations.AlterField(
            model_name='development_rule_feedback',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 838956), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='development_team',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 831956), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='development_team',
            name='team_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.development_team_status'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_received',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 814946), verbose_name='date received'),
        ),
        migrations.AlterField(
            model_name='product_release',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.project'),
        ),
        migrations.AlterField(
            model_name='product_release',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 841955), verbose_name='release date'),
        ),
        migrations.AlterField(
            model_name='product_release',
            name='release_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.release_status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 812939), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.project_manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.project_phase'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 811949), verbose_name='starting date'),
        ),
        migrations.AlterField(
            model_name='project_development',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 826954), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project_development',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 826954), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='project_development',
            name='development_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.development_status'),
        ),
        migrations.AlterField(
            model_name='project_development',
            name='required_skills',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project_development',
            name='scrum_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrummaster.project_manager'),
        ),
        migrations.AlterField(
            model_name='project_manager',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 809956), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project_plan',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 818956), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project_plan',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 818956), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='project_plan',
            name='deliverable',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project_plan',
            name='plan_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.project_manager'),
        ),
        migrations.AlterField(
            model_name='project_plan',
            name='plan_priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.priority'),
        ),
        migrations.AlterField(
            model_name='project_plan',
            name='plan_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.plan_status'),
        ),
        migrations.AlterField(
            model_name='project_plan_risk',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 822954), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project_plan_risk',
            name='risk_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.project_manager'),
        ),
        migrations.AlterField(
            model_name='project_plan_risk',
            name='risk_priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.priority'),
        ),
        migrations.AlterField(
            model_name='project_plan_risk',
            name='risk_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.risk_status'),
        ),
        migrations.AlterField(
            model_name='release_backlog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 847956), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='release_backlog',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.project_manager'),
        ),
        migrations.AlterField(
            model_name='release_feature',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.priority'),
        ),
        migrations.AlterField(
            model_name='release_feature',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.product_release'),
        ),
        migrations.AlterField(
            model_name='release_feature',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 843954), verbose_name='feature release date'),
        ),
        migrations.AlterField(
            model_name='release_strategy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 845956), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='release_strategy',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.project_manager'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 834957), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 834957), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='member_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.team_member_role'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='member_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.team_member_status'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 38, 21, 834957), verbose_name='start date'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Feedback_Recepient',
        ),
        migrations.DeleteModel(
            name='Feedback_Status',
        ),
    ]
