# Generated by Django 4.1.3 on 2022-12-14 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrummaster', '0002_remove_feedback_recepient_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_person',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 45, 980652), verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='contact_person_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 45, 978655), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='development_rule',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 46, 25653), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='development_rule_feedback',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 46, 27654), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='development_team',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 46, 16657), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_received',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 45, 990654), verbose_name='date received'),
        ),
        migrations.AlterField(
            model_name='product_release',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 46, 32657), verbose_name='release date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 45, 987655), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 45, 987655), verbose_name='starting date'),
        ),
        migrations.AlterField(
            model_name='project_development',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 46, 10656), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project_development',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 46, 10656), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='project_manager',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 45, 985655), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project_plan',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 45, 999655), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project_plan',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 45, 999655), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='project_plan_risk',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 46, 4654), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='release_backlog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 46, 40653), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='release_feature',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 46, 35660), verbose_name='feature release date'),
        ),
        migrations.AlterField(
            model_name='release_strategy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 46, 37656), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 46, 21654), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 46, 21654), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 39, 46, 21654), verbose_name='start date'),
        ),
    ]
