# Generated by Django 4.1.3 on 2022-12-14 20:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrummaster', '0003_alter_contact_person_registration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
        migrations.AddField(
            model_name='project_manager',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummaster.project'),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 679809), verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='contact_person_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 677818), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='development_rule',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 709807), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='development_rule_feedback',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 711809), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='development_team',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 703808), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_received',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 687809), verbose_name='date received'),
        ),
        migrations.AlterField(
            model_name='product_release',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 714809), verbose_name='release date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 682808), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 682808), verbose_name='starting date'),
        ),
        migrations.AlterField(
            model_name='project_development',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 699809), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project_development',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 698809), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='project_manager',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 684810), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project_plan',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 691809), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project_plan',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 691809), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='project_plan_risk',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 695809), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='release_backlog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 720809), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='release_feature',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 716811), verbose_name='feature release date'),
        ),
        migrations.AlterField(
            model_name='release_strategy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 718809), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 706809), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 706809), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 19, 14, 706809), verbose_name='start date'),
        ),
    ]
