# Generated by Django 4.1.3 on 2022-11-17 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceintegrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Manager_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Manager_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Manager_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_manager_name', models.CharField(max_length=200)),
                ('current_performance', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('service_integrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.service_integrator')),
                ('service_manager_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.service_manager_role')),
                ('service_manager_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.service_manager_status')),
                ('service_manager_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.service_manager_type')),
            ],
        ),
        migrations.CreateModel(
            name='service_management_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('service_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.service_manager')),
                ('task_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.task_status')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.task_type')),
            ],
        ),
    ]
