# Generated by Django 4.1.2 on 2022-11-11 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog_allocation_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('registration_date', models.DateTimeField(verbose_name='registration date')),
            ],
        ),
        migrations.CreateModel(
            name='Developer_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_status', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('expected_outcome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sprint_Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlog_item', models.TextField()),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('expected_outcome', models.TextField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer')),
                ('review_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.review_status')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint_Retrospective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrospective', models.TextField()),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint_Backlog_Allocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('allocation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.backlog_allocation_status')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer')),
                ('sprint_backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.sprint_backlog')),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='developer_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer_status'),
        ),
        migrations.AddField(
            model_name='developer',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.role'),
        ),
        migrations.AddField(
            model_name='developer',
            name='user_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Daily_Scrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('outcome', models.TextField()),
                ('sprint_backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.sprint_backlog')),
            ],
        ),
    ]
