# Generated by Django 4.1.2 on 2022-12-12 09:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.developer'),
        ),
        migrations.AlterField(
            model_name='daily_scrum',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 35, 11, 759823), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.developer_status'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 35, 11, 749824), verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.role'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='user_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='developer_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 35, 11, 747822), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 35, 11, 752824), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 35, 11, 751824), verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='sprint_backlog',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.developer'),
        ),
        migrations.AlterField(
            model_name='sprint_backlog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 35, 11, 753823), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='sprint_backlog_allocations',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 35, 11, 757823), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='sprint_retrospective',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 35, 11, 764823), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='sprint_review',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 35, 11, 762823), verbose_name='creation date'),
        ),
    ]
