# Generated by Django 4.1.2 on 2022-12-12 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_sprint_added_by_alter_daily_scrum_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_scrum',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 59, 20, 34520), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 59, 20, 25520), verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='developer_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 59, 20, 23521), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 59, 20, 27519), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 59, 20, 27519), verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='sprint_backlog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 59, 20, 29519), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='sprint_backlog_allocations',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 59, 20, 33521), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='sprint_retrospective',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 59, 20, 39522), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='sprint_review',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 59, 20, 37522), verbose_name='creation date'),
        ),
    ]
