# Generated by Django 4.1.3 on 2022-12-17 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_alter_daily_scrum_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_scrum',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 433288), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 408311), verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='developer_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 406312), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_received',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 418285), verbose_name='date received'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 415311), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 415311), verbose_name='starting date'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 423290), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 423290), verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='sprint_backlog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 427317), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='sprint_backlog_allocations',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 431312), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='sprint_retrospective',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 440287), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='sprint_review',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 438289), verbose_name='creation date'),
        ),
    ]
