# Generated by Django 4.1.3 on 2022-12-18 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '0004_alter_daily_scrum_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration_Tool_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Integration_Tool_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('integration_description', models.TextField()),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Integration_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Integrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pipeline_description', models.TextField()),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Pipeline_Item_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tool_Allocation_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Pipeline_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField()),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.service_pipeline')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.service_type')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.service_pipeline_item_status')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Integration_Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('description', models.TextField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer')),
                ('tool_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.integration_tool_status')),
                ('tool_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.integration_tool_type')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Integration_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.service_integration')),
                ('integrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.service_integrator')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.service_pipeline_item')),
            ],
        ),
        migrations.AddField(
            model_name='service_integration',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.service_integration_status'),
        ),
        migrations.CreateModel(
            name='Recommended_Adaptations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField()),
                ('date', models.DateTimeField(verbose_name='recommendation date')),
                ('integrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.service_integrator')),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer')),
            ],
        ),
        migrations.CreateModel(
            name='Integration_Tool_Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateTimeField(verbose_name='allocation date')),
                ('allocation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.tool_allocation_status')),
                ('integrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.service_integrator')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.service_integration_tool')),
            ],
        ),
        migrations.CreateModel(
            name='Integration_Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_date', models.DateTimeField(verbose_name='checkpoint date')),
                ('integrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.service_integrator')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.progress')),
            ],
        ),
        migrations.CreateModel(
            name='Integration_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.TextField()),
                ('completion_date', models.DateTimeField(verbose_name='completion date')),
                ('integrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceintegrator.service_integrator')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer')),
            ],
        ),
    ]
