# Generated by Django 4.1.3 on 2022-12-17 23:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_alter_daily_scrum_date_and_more'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='acquisition_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 586944), verbose_name='acquisition date'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resource_status'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resource_type'),
        ),
        migrations.AlterField(
            model_name='resource_manager',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 581950), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='resource_manager',
            name='resource_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_resource_management', to='developer.developer'),
        ),
        migrations.AlterField(
            model_name='resource_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 585945), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='resource_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 2, 51, 53, 583945), verbose_name='date created'),
        ),
    ]
