# Generated by Django 4.1.3 on 2022-12-18 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='acquisition_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 696638), verbose_name='acquisition date'),
        ),
        migrations.AlterField(
            model_name='resource_manager',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 691632), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='resource_status',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 694638), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='resource_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 3, 11, 20, 693636), verbose_name='date created'),
        ),
    ]
